export const collectionOptions = [
  { value: "", label: "Select theme..." },
  { value: "Books", label: "Books" },
  { value: "Coins", label: "Coins" },
  { value: "Stamps", label: "Stamps" },
  { value: "Postcards", label: "Postcards" },
  { value: "Comics", label: "Comics" },
  { value: "Action Figures", label: "Action Figures" },
  { value: "Trading Cards", label: "Trading Cards" },
  { value: "Vinyl Records", label: "Vinyl Records" },
  { value: "Movie Memorabilia", label: "Movie Memorabilia" },
  { value: "Sports Jerseys", label: "Sports Jerseys" },
  { value: "Autographs", label: "Autographs" },
  { value: "Art Prints", label: "Art Prints" },
  { value: "Antique Furniture", label: "Antique Furniture" },
  { value: "Vintage Clothing", label: "Vintage Clothing" },
  { value: "Toy Cars", label: "Toy Cars" },
  { value: "Dolls", label: "Dolls" },
  { value: "Model Trains", label: "Model Trains" },
  { value: "Musical Instruments", label: "Musical Instruments" },
  { value: "Movie Props", label: "Movie Props" },
  { value: "Fine China", label: "Fine China" },
  { value: "Wristwatches", label: "Wristwatches" },
  { value: "Jewelry", label: "Jewelry" },
  { value: "Comic Books", label: "Comic Books" },
  { value: "Bottles", label: "Bottles" },
  { value: "Sports Memorabilia", label: "Sports Memorabilia" },
  { value: "Board Games", label: "Board Games" },
  { value: "Vintage Cameras", label: "Vintage Cameras" },
  { value: "Sneakers", label: "Sneakers" },
  { value: "Figurines", label: "Figurines" },
  { value: "Vinyl Toys", label: "Vinyl Toys" },
  { value: "Vintage Posters", label: "Vintage Posters" },
  { value: "Concert Tickets", label: "Concert Tickets" },
  { value: "Vintage Magazines", label: "Vintage Magazines" },
  { value: "Musical Records", label: "Musical Records" },
  { value: "Action Cameras", label: "Action Cameras" },
  { value: "Snow Globes", label: "Snow Globes" },
  { value: "Candles", label: "Candles" },
  { value: "Shot Glasses", label: "Shot Glasses" },
  { value: "Beer Steins", label: "Beer Steins" },
  { value: "Vintage Maps", label: "Vintage Maps" },
  { value: "Pocket Knives", label: "Pocket Knives" },
  { value: "Keychains", label: "Keychains" },
  { value: "Trading Pins", label: "Trading Pins" },
  { value: "Artifacts", label: "Artifacts" },
  { value: "Antique Clocks", label: "Antique Clocks" },
  { value: "Hats", label: "Hats" },
  { value: "Lighters", label: "Lighters" },
  { value: "Fountain Pens", label: "Fountain Pens" },
  { value: "Vintage Telephones", label: "Vintage Telephones" },
  { value: "Vinyl Music Albums", label: "Vinyl Music Albums" },
  { value: "Other...", label: "Other..." },
];
